coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%

# Only post if coverage drops AND there are uncovered lines of code
comment:
  require_changes: "coverage_drop AND uncovered_patch"
ignore:
  - "cli/mocks"
  - "cli/main.go"
  - "cli/misc/logger/logger.go"
  - "cli/services/s3_service"
  - "cli/services/ui_service"
