coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 10%

# Only post if coverage drops AND there are uncovered lines of code
comment:
  require_changes: "coverage_drop AND uncovered_patch"
