name: Pull request

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write
  repository-projects: read

env:
  COVERAGE_COMMENT_TEXT: "go-test-coverage report:"

jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify labels
        uses: Brains-Beyond-Expectations/labeller@v1
        with:
          required_labels: |
            feature,enhancement,fix,bugfix,bug,chore
            major,minor,patch

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache-dependency-path: |
            cli/go.sum

      - name: Run tests with coverage
        run: |
          cd cli
          go test -race -coverprofile=coverage.out -covermode=atomic


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run build
        run: |
          cd cli
          go build
