name: Pull request

on:
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Run tests
        run: |
          cd cli
          go mod download
          go test
      - name: Run build
        run: |
          cd cli
          go build
